### ISSUE TITLE
Empty COPYING file will override LICENSE file

### ISSUE THREAD

**Issue by TheJJ** [licensee/licensee#553] opened 2022-04-17 16:34 UTC
### Describe the bug

licensee rather chooses the license of an empty file, than the obvious real license.
tested with `licensee (9.15.2)`.

### Steps to reproduce the behavior

- Have GPL-v3 in file LICENSE.
- Have empty file COPYING.
- no other files in the directory
- run licensee in that directory and observe:
the empty `COPYING` file will lead the resulting license to be NOASSERTION (an empty README.md is no problem tough):
```
License:        NOASSERTION
Matched files:  LICENSE, COPYING
LICENSE:
  Content hash:  7d4cdf499d39e2e1ce27b2878e22872f0f5a74dd
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-3.0
COPYING:
  Content hash:  da39a3ee5e6b4b0d3255bfef95601890afd80709
  License:       NOASSERTION
  Closest non-matching licenses:
    Zlib similarity:   0.00%
    WTFPL similarity:  0.00%
    Vim similarity:    0.00%
```

### Expected behavior

It should obviously detect GPL-3 instead of NOASSERTION.

**Comment by mlinksva** [comment] 2022-04-17 18:44
As mentioned in #554 and #555 licensee does not make an overall assertion if it encounters ambiguity, by design. An empty license (or copying, etc) file is contrived or ambiguous so I'm going to close this as wontfix.

**Closed by mlinksva** 2022-04-17 18:44 UTC
Labels: wontfix
